<?php
$page_title='Weekly Journal'; require_once 'includes/header.php'; $uid=(int)$user['id'];
$stmt=db()->prepare('SELECT * FROM journals WHERE user_id=? ORDER BY week_start DESC');$stmt->execute([$uid]);$journals=$stmt->fetchAll();
$currentWeek=date('Y-m-d',strtotime('monday this week'));$cur=db()->prepare('SELECT * FROM journals WHERE user_id=? AND week_start=? LIMIT 1');$cur->execute([$uid,$currentWeek]);$current=$cur->fetch();
$editorContent=$current?(string)$current['content']:'<p><br></p>';
if($current && strip_tags($editorContent)===$editorContent){$editorContent='<p>'.nl2br(e($editorContent)).'</p>';}
?>
<div class="page-intro"><div><span class="eyebrow">DOCUMENTATION</span><h2>Weekly Journal</h2><p>Document your OJT experience in a professional, Word-style editor with formatted text and images.</p></div><a class="btn secondary" href="journal_compilation.php">▤ Final Compilation</a></div>
<div class="journal-layout"><div>
<section class="panel journal-editor"><div class="panel-head"><div><span class="eyebrow">JOURNAL WORKSPACE</span><h3><?= $current?'Continue this week':'Start this week' ?></h3></div><span class="pill <?=($current&&$current['status']==='submitted')?'green-pill':'orange-pill'?>"><?=e(ucfirst($current['status']??'Draft'))?></span></div>
<form id="journalForm"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="journal_id" value="<?= (int)($current['id']??0)?>"><input type="hidden" name="content" id="journalContentValue" value="">
<div class="form-row"><label>Orientation<select name="orientation"><option value="portrait" <?=($current['orientation']??'portrait')==='portrait'?'selected':''?>>Portrait</option><option value="landscape" <?=($current['orientation']??'portrait')==='landscape'?'selected':''?>>Landscape</option></select></label><label>Week starting<input type="date" name="week_start" value="<?=e($current['week_start']??$currentWeek)?>" required></label><label>Week title<input name="title" value="<?=e($current['title']??'Weekly OJT Journal')?>" required></label></div>
<div class="document-editor-wrap"><div class="editor-toolbar" data-editor="journalEditor" role="toolbar" aria-label="Journal formatting tools">
<select class="editor-select" data-command="fontName" title="Font"><option value="Arial">Arial</option><option value="Calibri">Calibri</option><option value="Cambria">Cambria</option><option value="Georgia">Georgia</option><option value="Times New Roman">Times New Roman</option><option value="Verdana">Verdana</option><option value="Tahoma">Tahoma</option><option value="Trebuchet MS">Trebuchet MS</option><option value="Courier New">Courier New</option><option value="Palatino Linotype">Palatino</option></select><select class="editor-select editor-size" data-command="fontSize" title="Font size"><option value="2">10</option><option value="3" selected>12</option><option value="4">14</option><option value="5">18</option><option value="6">24</option><option value="7">32</option></select><button type="button" data-command="undo" title="Undo">↶</button><button type="button" data-command="redo" title="Redo">↷</button><span class="toolbar-divider"></span><button type="button" data-command="bold" title="Bold"><b>B</b></button><button type="button" data-command="italic" title="Italic"><i>I</i></button><button type="button" data-command="underline" title="Underline"><u>U</u></button><button type="button" data-command="strikeThrough" title="Strikethrough"><s>S</s></button><span class="toolbar-divider"></span>
<select class="editor-select editor-block" data-command="formatBlock" title="Paragraph style"><option value="p">Paragraph</option><option value="h1">Title</option><option value="h2">Heading 1</option><option value="h3">Heading 2</option><option value="blockquote">Quote</option></select><button type="button" data-command="insertUnorderedList" title="Bulleted list">• List</button><button type="button" data-command="insertOrderedList" title="Numbered list">1. List</button><button type="button" data-command="insertHorizontalRule" title="Horizontal line">―</button><span class="toolbar-divider"></span>
<button type="button" data-command="justifyLeft" title="Align left">≡</button><button type="button" data-command="justifyCenter" title="Center">≡</button><button type="button" data-command="justifyRight" title="Align right">≡</button><button type="button" data-command="justifyFull" title="Justify">☰</button><span class="toolbar-divider"></span>
<button type="button" data-editor-action="link" title="Insert link">↗ Link</button><button type="button" data-editor-action="image" title="Attach image">▧ Image</button><button type="button" data-editor-action="image-edit" title="Edit selected image">✎ Image</button><span class="toolbar-divider"></span><button type="button" data-image-layout="inline" title="Keep image in the text flow">↔ Inline</button><button type="button" data-image-layout="left" title="Wrap text to the right of the image">◀ Wrap</button><button type="button" data-image-layout="right" title="Wrap text to the left of the image">Wrap ▶</button><button type="button" data-image-layout="center" title="Center image on its own line">↔ Center</button><button type="button" data-command="removeFormat" title="Clear formatting">Tx</button><input type="file" id="journalImageInput" accept="image/png,image/jpeg,image/webp,image/gif" hidden></div>
<div id="journalEditor" class="rich-editor" contenteditable="true" role="textbox" aria-multiline="true" data-placeholder="Start writing your weekly OJT experience here..."><?= $editorContent ?></div></div>
<div class="editor-meta"><span id="wordCount">0 words</span><span id="saveState">Not saved</span></div><div class="editor-tip">Tip: You can format your entry, add lists, insert links, and attach photos directly inside the journal.</div><div class="form-actions"><button type="button" class="btn secondary" id="saveDraft">Save Draft</button><button type="submit" class="btn primary">Submit Journal</button></div></form></section>
<section class="panel"><div class="panel-head"><div><span class="eyebrow">TIMELINE</span><h3>Journal Timeline</h3></div><span class="muted"><?=count($journals)?> entries</span></div><div class="timeline">
<?php foreach($journals as $j):?><div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-body"><div class="timeline-top"><strong><?=e($j['title'])?></strong><span class="pill <?=$j['status']==='submitted'?'green-pill':'orange-pill'?>"><?=e(ucfirst($j['status']))?></span><button type="button" class="mini-edit" data-edit-journal='<?=e(json_encode(['id'=>$j['id'],'week_start'=>$j['week_start'],'title'=>$j['title'],'content'=>$j['content'],'orientation'=>$j['orientation']??'portrait'],JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'>Edit</button></div><div class="timeline-excerpt"><?=e(mb_strimwidth(trim(strip_tags($j['content'])),0,190,'…'))?></div><small>Week of <?=e(date('M d, Y',strtotime($j['week_start'])))?> · Updated <?=e(date('M d, Y h:i A',strtotime($j['updated_at'])))?></small></div></div><?php endforeach;?>
<?php if(!$journals):?><div class="empty">Your journal timeline will appear here.</div><?php endif;?></div></section></div>
<aside class="journal-side"><section class="panel"><div class="panel-head"><div><span class="eyebrow">DRAFTS</span><h3>Your Weekly Drafts</h3></div></div><div class="draft-list"><?php $drafts=array_filter($journals,fn($j)=>$j['status']==='draft'); if(!$drafts):?><div class="empty">No saved drafts.</div><?php else:foreach($drafts as $d):?><button type="button" class="draft-item" data-edit-journal='<?=e(json_encode(['id'=>$d['id'],'week_start'=>$d['week_start'],'title'=>$d['title'],'content'=>$d['content']],JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'><strong><?=e($d['title'])?></strong><span>Week of <?=e(date('M d, Y',strtotime($d['week_start'])))?></span></button><?php endforeach;endif;?></div></section>
<section class="panel journal-guide"><div class="guide-icon">▤</div><span class="eyebrow">DOCUMENT WORKFLOW</span><h3>Write it like a report</h3><p>Build each weekly entry with clear headings, paragraphs, lists, and supporting photos. You can still edit everything later in the final compilation.</p><div class="guide-list"><span>✓ Rich text formatting</span><span>✓ Image attachments</span><span>✓ Editable final compilation</span><span>✓ Print or save as PDF</span></div></section>
<section class="panel compilation-card"><div class="compilation-icon">✦</div><h3>Ready for final compilation?</h3><p>Combine every weekly entry into one editable document before printing or saving it as PDF.</p><a class="btn primary wide" href="journal_compilation.php">Open Compilation</a></section></aside></div>
<?php require_once 'includes/footer.php';?>
