<?php
require_once __DIR__ . '/helpers.php'; require_once __DIR__ . '/auth.php'; require_login();
$user=current_user(); if(!$user){header('Location: login.php');exit;}
$page=basename($_SERVER['PHP_SELF']); $flashes=get_flashes();
$profileImage=''; $profileImageFile=''; if(!empty($user['profile_image'])){ $profileImageFile=__DIR__.'/../uploads/profile/'.basename($user['profile_image']); if(is_file($profileImageFile)) $profileImage='uploads/profile/'.basename($user['profile_image']).'?v='.filemtime($profileImageFile); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($page_title??'Dashboard')?> | OJT360</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css">
<script>window.OJT360={csrf:<?=json_encode(csrf_token())?>,userId:<?= (int)$user['id']?>,base:<?=json_encode(rtrim(dirname($_SERVER['SCRIPT_NAME']),'/\\')==='/'?'':rtrim(dirname($_SERVER['SCRIPT_NAME']),'/\\'))?>,profileImage:<?=json_encode($profileImage)?>};</script></head>
<body><button class="sidebar-reveal" id="sidebarToggle" aria-label="Open navigation" title="Open navigation">☰</button><div class="sidebar-backdrop" id="sidebarBackdrop"></div><div class="app-shell" id="appShell">
<aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark logo-orbit" aria-label="OJT360 logo"><span class="orbit-dot orbit-dot-a"></span><span class="orbit-dot orbit-dot-b"></span><span class="orbit-dot orbit-dot-c"></span></div><div class="brand-copy"><strong>OJT360</strong><span>Student Portal</span></div></div>
<nav class="nav"><a class="<?= $page==='index.php'?'active':''?>" href="index.php"><span>⌂</span><em>Dashboard</em></a><a class="<?= $page==='attendance.php'?'active':''?>" href="attendance.php"><span>◷</span><em>Attendance</em></a><a class="<?= $page==='journal.php'?'active':''?>" href="journal.php"><span>▤</span><em>Journal</em></a><a class="<?= $page==='tasks.php'?'active':''?>" href="tasks.php"><span>✓</span><em>My Tasks</em></a><a class="<?= $page==='help.php'?'active':''?>" href="help.php"><span>?</span><em>Help & Support</em></a></nav>
<div class="sidebar-bottom"><a class="sidebar-setting" href="settings.php">⚙ <em>Settings</em></a><a class="mini-card" href="profile.php" title="Open your profile"><div class="avatar"><?php if($profileImage):?><img src="<?=e($profileImage)?>" alt="Profile picture"><?php else:?><?=e(initials($user['full_name']))?><?php endif;?></div><div class="mini-user"><strong><?=e($user['full_name'])?></strong><span><?=e($user['student_no'])?></span></div><span class="mini-profile-arrow" aria-hidden="true">›</span></a><button class="logout-link" data-logout>↪ <span>Logout</span></button></div></aside>
<main class="main"><header class="topbar"><div class="top-left"><button class="icon-btn mobile-only" id="menuBtn" aria-label="Open menu">☰</button><div><div class="eyebrow">STUDENT PORTAL</div><h1><?=e($page_title??'Dashboard')?></h1></div></div><div class="top-actions"><a class="icon-btn notification-btn" href="notifications.php" title="Notifications" aria-label="Notifications"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><?php $unread=(int)db()->query("SELECT COUNT(*) FROM notifications WHERE user_id=".(int)$user['id']." AND is_read=0")->fetchColumn(); if($unread>0):?><b class="notif-dot"><?=$unread>9?'9+':$unread?></b><?php endif;?></a><div class="profile-menu"><button type="button" class="profile-chip" id="profileMenuButton" aria-label="Open profile menu" aria-haspopup="true" aria-expanded="false"><div class="avatar small"><?php if($profileImage):?><img src="<?=e($profileImage)?>" alt="Profile picture"><?php else:?><?=e(initials($user['full_name']))?><?php endif;?></div></button><div class="profile-dropdown" id="profileDropdown" role="menu"><div class="profile-dropdown-head"><div class="avatar small"><?php if($profileImage):?><img src="<?=e($profileImage)?>" alt="Profile picture"><?php else:?><?=e(initials($user['full_name']))?><?php endif;?></div><div><strong><?=e($user['full_name'])?></strong><span><?=e($user['student_no'])?></span></div></div><a href="profile.php" role="menuitem">View Profile <span>›</span></a><button type="button" id="headerUploadProfile" role="menuitem">Upload Profile <span>↑</span></button><button type="button" id="headerDeleteProfile" class="profile-delete" role="menuitem">Delete Profile <span>×</span></button></div><input type="file" id="headerProfileInput" accept="image/jpeg,image/png,image/webp" hidden></div></div></header>
<?php foreach($flashes as $f):?><div class="flash <?=e($f['type'])?>"><?=e($f['message'])?></div><?php endforeach;?>
